"use client";

import { doc, getDoc, serverTimestamp, setDoc } from "firebase/firestore";
import { Building2, CheckCircle2, LoaderCircle, Save } from "lucide-react";
import { type FormEvent, useEffect, useState } from "react";
import { useAuth } from "@/context/AuthContext";
import { db } from "@/lib/firebase";

type AgencyProfile = { name: string; username: string; description: string };
const empty: AgencyProfile = { name: "", username: "", description: "" };

export default function AgencyProfilePage() {
  const { user } = useAuth(); const [agency, setAgency] = useState<AgencyProfile>(empty); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [notice, setNotice] = useState("");
  useEffect(() => { if (!user) return; void getDoc(doc(db, "agencies", user.uid)).then((snapshot) => { const data = snapshot.data(); setAgency({ name: typeof data?.name === "string" ? data.name : "", username: typeof data?.username === "string" ? data.username : "", description: typeof data?.description === "string" ? data.description : "" }); }).catch(() => setNotice("We could not load the agency profile.")).finally(() => setLoading(false)); }, [user]);
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!user) return; setSaving(true); setNotice(""); try { await setDoc(doc(db, "agencies", user.uid), { uid: user.uid, email: user.email ?? "", name: agency.name.trim(), username: agency.username.trim().replace(/^@/, ""), description: agency.description.trim(), updatedAt: serverTimestamp() }, { merge: true }); setNotice("Agency profile saved. New briefs will now use this agency identity."); } catch { setNotice("We could not save the agency profile. Please try again."); } finally { setSaving(false); } }
  if (loading) return <div className="flex min-h-[60vh] items-center justify-center"><LoaderCircle className="size-7 animate-spin text-brand-blue" /></div>;
  return <div className="mx-auto max-w-3xl"><header><p className="text-sm font-bold tracking-[0.18em] text-brand-blue">AGENCY PROFILE</p><h1 className="mt-1 text-3xl font-bold">Your agency identity.</h1><p className="mt-2 text-slate-600">This is the name Actors see on your briefs and throughout CASTARZ.</p></header><form onSubmit={save} className="mt-7 rounded-3xl bg-white p-5 shadow-sm ring-1 ring-brand-silver/70 sm:p-7"><div className="flex size-14 items-center justify-center rounded-2xl bg-brand-navy text-brand-cyan"><Building2 className="size-7" /></div><div className="mt-6 grid gap-5 sm:grid-cols-2"><Field label="Agency name" value={agency.name} set={(name) => setAgency({ ...agency, name })} placeholder="e.g. Mosaic Casting" required /><Field label="Username" value={agency.username} set={(username) => setAgency({ ...agency, username })} placeholder="e.g. mosaiccasting" prefix="@" required /></div><label className="mt-5 block"><span className="mb-2 block text-sm font-bold text-slate-700">About your agency</span><textarea value={agency.description} onChange={(event) => setAgency({ ...agency, description: event.target.value })} rows={4} placeholder="Tell actors what your agency is known for." className="w-full rounded-xl border border-slate-300 px-4 py-3 outline-none focus:border-brand-blue focus:ring-4 focus:ring-brand-cyan/20" /></label>{notice && <p className="mt-5 flex items-center gap-2 rounded-xl bg-brand-ice px-4 py-3 text-sm font-semibold text-brand-navy"><CheckCircle2 className="size-5 text-brand-blue" />{notice}</p>}<button disabled={saving} className="mt-6 flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-brand-blue font-bold text-white hover:bg-brand-navy disabled:opacity-50">{saving ? <LoaderCircle className="size-5 animate-spin" /> : <Save className="size-5" />}{saving ? "Saving…" : "Save agency profile"}</button></form></div>;
}
function Field({ label, value, set, placeholder, prefix, required }: { label: string; value: string; set: (value: string) => void; placeholder: string; prefix?: string; required?: boolean }) { return <label><span className="mb-2 block text-sm font-bold text-slate-700">{label}</span><div className="relative">{prefix && <span className="absolute inset-y-0 left-4 flex items-center font-bold text-slate-400">{prefix}</span>}<input required={required} value={value} onChange={(event) => set(event.target.value)} placeholder={placeholder} className={`min-h-12 w-full rounded-xl border border-slate-300 px-4 outline-none focus:border-brand-blue focus:ring-4 focus:ring-brand-cyan/20 ${prefix ? "pl-8" : ""}`} /></div></label>; }
