"use client";

import { doc, getDoc } from "firebase/firestore";
import Image from "next/image";
import { LoaderCircle, MapPin, ShieldCheck, UserRound } from "lucide-react";
import { useEffect, useState } from "react";
import { db } from "@/lib/firebase";

interface SharedActor { uid: string; fullName: string; stageName: string; headshot: string; bio: string; heightCm: string; hairColor: string; eyeColor: string; ageRange: string; }
interface SharedShortlist { briefTitle: string; publicActors: SharedActor[]; }

export default function SharedShortlistPage({ params }: { params: Promise<{ shortlistId: string }> }) {
  const [shortlist, setShortlist] = useState<SharedShortlist | null>(null); const [loading, setLoading] = useState(true);
  useEffect(() => { void params.then(async ({ shortlistId }) => { try { const snapshot = await getDoc(doc(db, "shortlists", shortlistId)); if (snapshot.exists()) { const data = snapshot.data(); setShortlist({ briefTitle: typeof data.briefTitle === "string" ? data.briefTitle : "Casting shortlist", publicActors: Array.isArray(data.publicActors) ? data.publicActors : [] }); } } finally { setLoading(false); } }); }, [params]);
  if (loading) return <main className="flex min-h-dvh items-center justify-center bg-brand-ice"><LoaderCircle className="size-7 animate-spin text-brand-blue" /></main>;
  if (!shortlist) return <main className="flex min-h-dvh items-center justify-center bg-brand-ice p-5"><section className="max-w-md rounded-3xl bg-white p-8 text-center shadow-sm ring-1 ring-brand-silver"><h1 className="text-2xl font-bold text-brand-navy">This shortlist is unavailable.</h1><p className="mt-3 text-slate-600">Please ask your casting contact for a current guest link.</p></section></main>;
  return <main className="min-h-dvh bg-brand-ice px-4 py-8 sm:px-8"><div className="mx-auto max-w-5xl"><header className="rounded-3xl bg-brand-navy p-7 text-white sm:p-10"><p className="text-sm font-bold tracking-[0.2em] text-brand-cyan">CASTARZ · PRIVATE SHORTLIST</p><h1 className="mt-3 text-3xl font-bold sm:text-4xl">{shortlist.briefTitle}</h1><p className="mt-3 max-w-2xl text-slate-300">A curated selection from your casting agency. Only the actors approved for this brief are shown here.</p><p className="mt-6 flex items-center gap-2 text-sm font-semibold text-brand-cyan"><ShieldCheck className="size-4" />Confidential production review</p></header><section className="mt-7 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{shortlist.publicActors.map((actor) => <article key={actor.uid} className="overflow-hidden rounded-3xl bg-white shadow-sm ring-1 ring-brand-silver/70"><div className="flex aspect-[4/3] items-center justify-center bg-brand-ice">{actor.headshot ? <Image src={actor.headshot} alt={actor.stageName || actor.fullName} width={600} height={450} unoptimized className="size-full object-cover" /> : <UserRound className="size-12 text-brand-blue" />}</div><div className="p-5"><h2 className="text-xl font-bold text-brand-navy">{actor.stageName || actor.fullName}</h2>{actor.stageName && <p className="mt-1 text-sm text-slate-500">{actor.fullName}</p>}<div className="mt-4 flex flex-wrap gap-2">{[actor.ageRange, actor.heightCm && `${actor.heightCm}cm`, actor.hairColor, actor.eyeColor].filter(Boolean).map((spec) => <span key={spec} className="rounded-full bg-brand-ice px-3 py-1 text-xs font-bold text-brand-navy">{spec}</span>)}</div>{actor.bio && <p className="mt-4 text-sm leading-6 text-slate-600">{actor.bio}</p>}</div></article>)}</section>{!shortlist.publicActors.length && <div className="mt-7 rounded-3xl bg-white p-10 text-center shadow-sm ring-1 ring-brand-silver"><MapPin className="mx-auto size-8 text-brand-blue" /><p className="mt-4 font-bold">This shortlist has no actors yet.</p></div>}</div></main>;
}
